### ISSUE TITLE
Add file extensions support

### ISSUE THREAD

**Issue by fsmaia** [sodatea/vscode-velocity#4]
It would be nice to have support to adding file extensions to Velocity language mode. In the company I work, as a sample, we also use prop and inc file extensions as Velocity files.

Maybe this settings just belongs to VSCode language mode engine.

**Comment by haoqunjiang** [comment]
This can be done without modifying this extension, as [documented on the VSCode website](https://code.visualstudio.com/docs/customization/colorizer#_common-questions):

> Q: Can I add more file extensions to an existing colorizer?
> 
> A: Yes. To extend an existing colorizer, you would create a simple `package.json` in a new folder under `.vscode/extensions` and provide the `extensionDependencies` attribute specifying the customization you want to add to.
